version: "3.8"

services:
  hp_search:
    build:
      context: ./
      dockerfile: Dockerfile_os_sbrtVSnone
    volumes:
      - ../deepsurv/:/deepsurv
      - ./logs:/shared/logs
      - ../experiments/data/:/shared/data